name: Deploy to DirectAdmin via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        
    - name: Install Dependencies (Composer)
      run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install NPM Dependencies & Build
      run: |
        npm install
        npm run build

    - name: Prepare Deployment Files
      run: |
        # Buat script unzip php
        cat << 'EOF' > unzip.php
        <?php
        $zip = new ZipArchive;
        $res = $zip->open('deploy.zip');
        if ($res === TRUE) {
            $zip->extractTo(__DIR__);
            $zip->close();
            unlink('deploy.zip');
            unlink(__FILE__);
            echo 'OK';
        } else {
            echo 'FAILED';
        }
        ?>
        EOF
        
        # Zip semua file kecuali yang tidak perlu
        zip -r deploy.zip . -x "*.git*" "node_modules/*" ".env.example" ".github/*" "unzip.php" "deploy.zip"

    - name: Upload Zip to Server
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        lftp -c "
        set ftp:ssl-allow yes
        set ssl:verify-certificate no
        set net:timeout 30
        open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER
        cd /domains/ssb-sumberharjo.web.id/public_html/
        put deploy.zip
        put unzip.php
        "

    - name: Extract Files on Server
      run: |
        curl -sS https://ssb-sumberharjo.web.id/unzip.php
