name: Deploy to DirectAdmin via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Install Dependencies (Composer)
      run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install NPM Dependencies & Build
      run: |
        npm install
        npm run build

    - name: Sync files to DirectAdmin (FTP)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /domains/ssb-sumberharjo.web.id/public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env.example
          .github/**
